export const COOFFES = [
  {
    id: "1",
    imgUrl: "/typeCoffe/Expresso.svg",
    type: ["TRADICIONAL", "ESPECIAL"],
    name: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    price: 9.99,
  },
  {
    id: "2",
    imgUrl: "/typeCoffe/Americano.svg",
    type: ["TRADICIONAL"],
    name: "Expresso Americano",
    description: "Expresso diluído, menos intenso que o tradicional",
    price: 10.99,
  },
  {
    id: "3",
    imgUrl: "/typeCoffe/ExpressoCremoso.svg",
    type: ["TRADICIONAL"],
    name: "Expresso Cremoso",
    description: "Café expresso tradicional com espuma cremosa",
    price: 15.99,
  },
  {
    id: "4",
    imgUrl: "/typeCoffe/CafeGelado.svg",
    type: ["TRADICIONAL"],
    name: "Expresso Gelado",
    description: "Bebida preparada com café expresso e cubos de gelo",
    price: 9.99,
  },
  {
    id: "5",
    imgUrl: "/typeCoffe/CafecomLeite.svg",
    type: ["TRADICIONAL"],
    name: "Café com Leite",
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    price: 10.99,
  },
  {
    id: "6",
    imgUrl: "/typeCoffe/Latte.svg",
    type: ["TRADICIONAL"],
    name: "Latte",
    description:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    price: 15.99,
  },
  {
    id: "7",
    imgUrl: "/typeCoffe/Capuccino.svg",
    type: ["TRADICIONAL"],
    name: "Capuccino",
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    price: 9.99,
  },
  {
    id: "8",
    imgUrl: "/typeCoffe/Macchiato.svg",
    type: ["TRADICIONAL"],
    name: "Macchiato",
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    price: 10.99,
  },
  {
    id: "9",
    imgUrl: "/typeCoffe/Mochaccino.svg",
    type: ["TRADICIONAL"],
    name: "Mocaccino",
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: 15.99,
  },
  {
    id: "10",
    imgUrl: "/typeCoffe/ChocolateQuente.svg",
    type: ["ESPECIAL"],
    name: "Chocolate Quente",
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    price: 9.99,
  },
  {
    id: "11",
    imgUrl: "/typeCoffe/CafecomLeite.svg",
    type: ["TRADICIONAL"],
    name: "Café com Leite",
    description: "Meio a meio de expresso tradicional com leite vaporizado",
    price: 10.99,
  },
  {
    id: "12",
    imgUrl: "/typeCoffe/Cubano.svg",
    type: ["ESPECIAL"],
    name: "Cubano",
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    price: 15.99,
  },
  {
    id: "13",
    imgUrl: "/typeCoffe/Havaiano.svg",
    type: ["ESPECIAL"],
    name: "Havaiano",
    description: "Bebida adocicada preparada com café e leite de coco",
    price: 9.99,
  },
  {
    id: "14",
    imgUrl: "/typeCoffe/Arabe.svg",
    type: ["ESPECIAL"],
    name: "Árabe",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    price: 10.99,
  },
  {
    id: "15",
    imgUrl: "/typeCoffe/Irlandes.svg",
    type: ["ESPECIAL"],
    name: "Irlandês",
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    price: 15.99,
  },
];
